---
- name: Converge
  hosts: all
  vars:
    nu_plugins:
      - nu_plugin_query
    nu_users:
      - ansible
  tasks:
    - name: "Include yethal.nushell"
      ansible.builtin.include_role:
        name: yethal.nushell
