---
- name: Converge
  hosts: all
  vars:
    nushell_version: 0.101.0
    nu_plugins:
      - nu_plugin_example
      - nu_plugin_gstat
      - nu_plugin_inc
      - nu_plugin_query
    nu_users:
      - ansible
  tasks:
    - name: "Include yethal.nushell"
      ansible.builtin.include_role:
        name: yethal.nushell
