---
- name: Converge
  hosts: all
  roles:
    - role: yethal.nushell
  vars:
    nushell_version: 0.71.0
    plugins:
      - nu_plugin_example
      - nu_plugin_gstat
      - nu_plugin_inc
      - nu_plugin_query
    nu_users:
      - ansible
