---
- name: Verify
  hosts: all
  vars_files:
    - ../../vars/main.yml
  vars:
    expected_version: 0.87.0
    nu_users:
      - ansible
  tasks:
    - name: Include default assertions
      ansible.builtin.include_tasks: "../common/{{ file }}.yml"
      loop:
        - binary
        - configs
        - plugins
        - shell
        - banner
        - profile
        - variant
      loop_control:
        loop_var: file

    - name: Get nushell version
      ansible.builtin.shell: # noqa command-instead-of-shell
        cmd: "version|get version"
        executable: "/usr/local/bin/nu"
      register: version_to_check
      changed_when: false

    - name: Assert nushell version is the same as specified during converge
      ansible.builtin.assert:
        that: version_to_check.stdout == expected_version
        quiet: true
