---
- name: nushell
  hosts: all
  become: false
  tasks:
    - name: Vars
      ansible.builtin.include_vars: defaults/main.yml
    - name: Install
      ansible.builtin.include_tasks: tasks/main.yml
