---
- name: Converge
  hosts: all
  vars:
    nu_users:
      - runner
    set_shell: true
    add_to_profile: true
  pre_tasks:
    - name: Fail if not running on MacOS
      ansible.builtin.fail:
        msg: "This test should only run on MacOS"
      when: ansible_system != 'Darwin'
  tasks:
    - name: "Include yethal.nushell"
      ansible.builtin.include_role:
        name: yethal.nushell
