---
- name: Create plugins config file
  ansible.builtin.file:
    state: touch
    access_time: preserve
    modification_time: preserve
    path: "{{ item.homedir }}/{{ nushell_config_path }}/plugin.msgpackz"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: "0644"
  loop: "{{ home_dirs }}"
  loop_control:
    label: "{{ item.user }}"

- name: Register all plugins
  ansible.builtin.command:
    argv:
      - "{{ nushell_binary_path }}/nu"
      - --plugin-config "{{ item[0].homedir }}/{{ nushell_config_path }}/plugin.msgpackz"
      - -c "plugin add {{ nushell_binary_path }}/{{ item[1] }}"
  loop: "{{ home_dirs | product(nu_plugins) }}"
  loop_control:
    label: "{{ item[0].user }} {{ item[1] }}"
  changed_when: false
