- name: Check installed nushell version
  ansible.builtin.shell:  # noqa command-instead-of-shell
    cmd: "version | get version"
    executable: "{{ install_path }}/nu"
  register: installed
  changed_when: installed_version is not defined

- name: Set installed nushell version as fact
  ansible.builtin.set_fact:
    installed_version: "{{ installed.stdout }}"

- name: Update nushell to latest version
  when: nushell_version == 'latest'
  block:
    - name: Call GitHub api to get newest version number
      ansible.builtin.uri:
        url: "{{ releases_endpoint }}/latest"
      register: api_response
      run_once: yes

    - name: Set latest nushell version as fact
      ansible.builtin.set_fact:
        latest_version: "{{ api_response.json | json_query('tag_name') }}"

    - name: Install nushell
      ansible.builtin.import_tasks: install.yml
      when: installed_version != latest_version

- name: Update nushell to specific version
  when: nushell_version != ('latest' or installed_version)
  ansible.builtin.import_tasks: install.yml