---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
provisioner:
  name: ansible
  log: false
  playbooks:
    prepare: ../common/prepare.yml
verifier:
  name: ansible
