---
- name: Verify
  hosts: all
  vars_files:
    - ../../vars/main.yml
  vars:
    nu_users:
      - ansible
  tasks:
    - name: Include default assertions
      ansible.builtin.include_tasks: "../common/{{ file }}.yml"
      loop:
        - binary
        - configs
        - plugins
        - shell
        - banner
        - profile
      loop_control:
        loop_var: file

    - name: Get list of features
      ansible.builtin.shell: # noqa command-instead-of-shell
        cmd: "version|get features"
        executable: "{{ nushell_binary_path }}/nu"
      become_user: "{{ item }}"
      become: true
      register: features
      changed_when: false
      loop: "{{ nu_users }}"

    - name: Verify dataframes feature is present
      ansible.builtin.assert:
        that: "'dataframe' in item.stdout"
        quiet: true
      loop: "{{ features.results }}"
      loop_control:
        label: "{{ item.item }}"
