---
- name: Converge
  hosts: all
  vars:
    install_configs: none
    nu_users:
      - ansible
  tasks:
    - name: "Include yethal.nushell"
      ansible.builtin.include_role:
        name: yethal.nushell
