---
- name: Assert banner is not disabled
  ansible.builtin.lineinfile:
    path: "/home/{{ item }}/{{ nushell_config_path }}/config.nu"
    state: absent
    regexp: "^\\$env\\.config\\.show_banner = (true|false)\\s*$"
  check_mode: true
  register: banner
  failed_when: banner is changed
  loop: "{{ nu_users }}"
