---
- name: Get nushell install path
  ansible.builtin.stat:
    path: "{{ nushell_binary_path }}/nu"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: nu_path

- name: Assert nushell binary is present
  ansible.builtin.assert:
    that: nu_path.stat.exists
    quiet: true
