---
- name: Set config files as fact
  ansible.builtin.set_fact:
    config_urls:
      - name: config.nu
      - name: env.nu
      - name: login.nu

- name: Stat config files
  ansible.builtin.stat:
    path: "/{{'Users' if ansible_system == 'Darwin' else 'home'}}/{{ item[0] }}/{{ nushell_config_path }}/{{ item[1] }}"
  loop: "{{ nu_users | product(config_urls | map(attribute='name')) }}"
  loop_control:
    label: "{{ item[0] }} - {{ item[1] }}"
  register: configs

- name: Assert config files are present
  ansible.builtin.assert:
    that: configs.results | map(attribute='stat.exists') is all
    quiet: true
