---

- name: Stat config files
  ansible.builtin.stat:
    path: "/home/{{ item }}/{{ nushell_config_path }}/config.nu"
    get_attributes: false
    get_checksum: false
    get_mime: false
  loop: "{{ nu_users }}"
  loop_control:
    label: "{{ item }}"
  register: configs

- name: Assert config files are present
  ansible.builtin.assert:
    that: configs.results | map(attribute='stat.exists') is all
    quiet: true
