---
- name: Prepare
  hosts: all
  vars:
    nu_users:
      - ansible
  tasks:
    - name: Set name of sudo group as fact
      ansible.builtin.set_fact:
        sudo_group: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"

    - name: Create group {{ sudo_group }}
      ansible.builtin.group:
        name: "{{ sudo_group }}"
        state: present

    - name: Enable passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%{{ sudo_group }}'
        line: '%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Create nonroot users
      ansible.builtin.user:
        state: present
        name: "{{ item }}"
        group: "{{ sudo_group }}"
        shell: /bin/bash
        append: true
      loop: "{{ nu_users }}"
