---
- name: Assert nu was not added to .profile
  ansible.builtin.lineinfile:
    path: "/home/{{ item }}/.profile"
    line: "/usr/local/bin/nu -l"
    state: absent
  check_mode: true
  register: profile
  failed_when: profile.changed
  loop: "{{ nu_users }}"
