---
- name: Get list of features
  ansible.builtin.shell: # noqa command-instead-of-shell
    cmd: "version|get features"
    executable: "/usr/local/bin/nu"
  become_user: "{{ item }}"
  become: true
  register: features
  changed_when: false
  loop: "{{ nu_users }}"

- name: Verify dataframes feature is absent
  ansible.builtin.assert:
    that: "'dataframe' not in item.stdout"
    quiet: true
  loop: "{{ features.results }}"
  loop_control:
    label: "{{ item.item }}"
