---
- name: Converge
  hosts: all
  vars:
    disable_banner: true
    add_hostname_to_prompt: true
    clear_login_file: true
    nu_users:
      - ansible
  tasks:
    - name: "Include yethal.nushell"
      ansible.builtin.include_role:
        name: yethal.nushell
