---
- name: Verify
  hosts: all
  vars_files:
    - ../../vars/main.yml
  vars:
    nu_users:
      - ansible
    nushell_binary_path: /usr/local/bin
  tasks:
    - name: Include default assertions
      ansible.builtin.include_tasks: "../common/{{ file }}.yml"
      loop:
        - binary
        - configs
        - plugins
        - shell
        - profile
        - variant
      loop_control:
        loop_var: file

    - name: Assert banner is disabled
      ansible.builtin.lineinfile:
        path: "/home/{{ item }}/{{ nushell_config_path }}/config.nu"
        state: present
        backrefs: true
        regexp: '^(\s*)show_banner: (true|false)(.*)$'
        line: '\1show_banner: false\3'
      check_mode: true
      register: banner
      failed_when: banner is changed
      loop: "{{ nu_users }}"

    - name: Assert hostname was added to prompt
      ansible.builtin.lineinfile:
        path: "/home/{{ item }}/{{ nushell_config_path }}/config.nu"
        state: present
        regexp: "^.*PROMPT_INDICATOR.*$"
        line: "$env.PROMPT_INDICATOR = '({{ inventory_hostname }})〉'"
      check_mode: true
      register: hostname_prompt
      failed_when: hostname_prompt is changed
      loop: "{{ nu_users }}"

    - name: Run nushell command to check for config errors
      ansible.builtin.command:
        argv:
          - /usr/local/bin/nu
          - --no-config-file
          - --no-history
          - --commands
          - 'nu-check --debug /home/{{ item }}/{{ nushell_config_path }}/config.nu'
      changed_when: false
      register: check_output
      failed_when: check_output.stdout != 'true'
      loop: "{{ nu_users }}"
