---
- name: Verify
  hosts: all
  vars_files:
    - ../../vars/main.yml
  vars:
    nu_users:
      - ansible
  tasks:
    - name: Include default assertions
      ansible.builtin.include_tasks: "../common/{{ file }}.yml"
      loop:
        - binary
        - configs
        - plugins
        - shell
        - profile
      loop_control:
        loop_var: file

    - name: Assert banner is disabled
      ansible.builtin.lineinfile:
        path: "/home/{{ item }}/{{ nushell_config_path }}/config.nu"
        state: present
        backrefs: true
        regexp: '^(\s*)show_banner: (true|false)(.*)$'
        line: '\1show_banner: false\3'
      check_mode: yes
      register: banner
      failed_when: banner is changed
      loop: "{{ nu_users }}"

    - name: Run nushell command to check for config errors
      ansible.builtin.command: "nu --config /home/{{ item }}/{{ nushell_config_path }}/config.nu -c help"
      changed_when: false
      register: help_output
      loop: "{{ nu_users }}"

    - name: Assert exit code was correct
      ansible.builtin.assert:
        that: item == 0
        quiet: true
      loop: "{{ help_output.results | map(attribute='rc') | list }}"
