---
- name: Verify
  hosts: all
  vars_files:
    - ../../vars/main.yml
  vars:
    nu_users:
      - ansible
  tasks:
    - name: Include default assertions
      ansible.builtin.include_tasks: "../common/{{ file }}.yml"
      loop:
        - binary
        - configs
        - plugins
        - shell
        - profile
      loop_control:
        loop_var: file

    - name: Assert banner is disabled
      ansible.builtin.lineinfile:
        path: "/home/{{ item }}/{{ nushell_config_path }}/config.nu"
        state: present
        backrefs: true
        regexp: '^(\s*)show_banner: (true|false)(.*)$'
        line: '\1show_banner: false\3'
      check_mode: true
      register: banner
      failed_when: banner is changed
      loop: "{{ nu_users }}"

    - name: Assert hostname was added to prompt
      ansible.builtin.lineinfile:
        path: "/home/{{ item }}/{{ nushell_config_path }}/env.nu"
        state: present
        regexp: "^.*PROMPT_INDICATOR.*$"
        line: "$env.PROMPT_INDICATOR = '({{ inventory_hostname }})〉'"
      check_mode: true
      register: hostname_prompt
      failed_when: hostname_prompt is changed
      loop: "{{ nu_users }}"

    - name: Run nushell command to check for config errors
      ansible.builtin.command: "nu -n -c 'nu-check /home/{{ item[0] }}/{{ nushell_config_path }}/{{ item[1] }}'"
      changed_when: false
      register: check_output
      failed_when: check_output.stdout != 'true'
      loop: "{{ nu_users|product(['config.nu', 'env.nu', 'login.nu']) }}"
      loop_control:
        label: '{{ item[0] }} - {{ item[1] }}'
