---
- name: Remove temp configs
  ansible.builtin.file:
    path: "/tmp/nushell"
    state: absent

- name: Remove download directory
  ansible.builtin.file:
    path: "/tmp/{{ nushell_package }}"
    state: absent
