---
- name: Converge
  hosts: all
  vars:
    nu_users:
      - ansible
    overwrite_configs: true
  tasks:
    - name: "Include yethal.nushell"
      ansible.builtin.include_role:
        name: yethal.nushell
