---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  vars:
    nu_users:
      - ansible
  tasks:
    - name: Include default assertions
      ansible.builtin.include_tasks: "../common/{{ file }}.yml"
      loop:
        - binary
        - configs
        - plugins
        - shell
        - banner
        - profile
      loop_control:
        loop_var: file
