---
- name: Verify
  hosts: all
  vars_files:
    - ../../vars/main.yml
  vars:
    add_to_profile: true
    nu_users:
      - ansible
  tasks:
    - name: Include default assertions
      ansible.builtin.include_tasks: "../common/{{ file }}.yml"
      loop:
        - binary
        - configs
        - plugins
        - shell
        - banner
        - variant
      loop_control:
        loop_var: file

    - name: Assert nu was added to .profile
      ansible.builtin.lineinfile:
        path: "/home/{{ item }}/.profile"
        line: "/usr/local/bin/nu -l"
        state: present
      check_mode: true
      register: profile
      failed_when: profile.changed
      loop: "{{ nu_users }}"
