---
name: CI
"on":
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: "yethal.nushell"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.tests-list.outputs.tests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: "yethal.nushell"

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Run ansible-lint
        run: ansible-lint . --exclude molecule/common/*

      - name: Generate test list
        id: tests-list
        run: echo "tests=$(ls molecule | grep -v "common" | jq -sRc 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu2004
          - ubuntu2404
        scenario: ${{ fromJson(needs.lint.outputs.tests) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: "yethal.nushell"

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run ${{ matrix.scenario }} test
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
